version: 2.1

# orbs:
  # ruby: circleci/ruby@0.1.2

jobs:
  build:
    working_directory: ~/articles_catalog

    # Primary container image where all commands run

    docker:
      - image: circleci/ruby:2.7.1
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_PATH: vendor/bundle
          BUNDLE_RETRY: 3
          BUNDLER_VERSION: 2.2.5
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          PG_HOST: 127.0.0.1
          PGUSER: root

    # Service container image available at `host: localhost`

      - image: circleci/postgres:12.0
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: articles_catalog_test

    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - rails-demo-{{ checksum "Gemfile.lock" }}
            - rails-demo-

      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      - run: sudo apt install -y postgresql-client || true

      # Store bundle cache
      - save_cache:
          key: rails-demo-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:structure:load

      - run:
          name: Parallel RSpec
          command: bin/rails test

      # Save artifacts
      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2
  integration:
    jobs:
      - build

# executors:
#   default:
#     working_directory: ~/articles_catalog
#     docker:
#       - image: circleci/ruby:2.7.1
#         environment:
#           BUNDLE_JOBS: 3
#           BUNDLE_PATH: vendor/bundle
#           BUNDLE_RETRY: 3
#           BUNDLER_VERSION: 2.2.5
#           RAILS_ENV: test
#           DB_HOST: 127.0.0.1
#           PG_HOST: 127.0.0.1
#       - image: circleci/postgres:12.0
#         environment:
#           POSTGRES_DB: articles_catalog_test

# commands:
#   configure_bundler:
#     description: Configure bundler
#     steps:
#       - run:
#           name: Configure bundler
#           command: |
#             echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
#             source $BASH_ENV
#             gem install bundler
# jobs:
#   build:
#     executor: default
#     steps:
#       - checkout
#       - restore_cache:
#           keys:
#             - hix-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
#             - hix-
#       - configure_bundler
#       - run:
#           name: Install bundle
#           command: bundle install
#       - run:
#           name: Wait for DB
#           command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
#       - run:
#           name: Install postgresql client
#           command: sudo apt-get -t stable install postgresql-client --fix-missing
#       - run:
#           name: Setup DB
#           command: bundle exec rails db:create db:schema:load --trace
#       - run:
#           name: RSpec
#           command: |
#             bundle exec rspec --profile 10 \
#                               --format progress
#       - save_cache:
#           key: hix-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
#           paths:
#             - vendor/bundle