RemoveUnusedMethodsInControllersCheck: {
  except_methods: [
    'ArticlesController#create',
    'Readers::ArticlesController#index',
    'Readers::ArticlesController#show',
    'Admins::AdminsController#show',
    'Admins::ArticleUploadsController#upload'
  ]
}